package com.cybermath;

import java.sql.*;

/**
 * GestorDB — Capa de persistencia con H2 (base de datos embebida).
 * Reemplaza a GestorArchivos.java (serialización binaria).
 *
 * Ubicación del archivo: ~/CyberMathSaves/cybermath.mv.db
 * No requiere servidor externo ni instalación adicional.
 *
 * ESQUEMA:
 *   partidas  (slot, nombre, integridad, criptos, niveles_completados TEXT)
 *   historial (id, slot, nivel, resultado, fecha)
 */
public class GestorDB {

    // --- Conexión única (singleton) reutilizada en toda la sesión ---
    private static Connection conexion = null;

    // Ruta del archivo H2 en el directorio del usuario
    private static final String RUTA_DB =
            "jdbc:h2:" + System.getProperty("user.home")
                    + "/CyberMathSaves/cybermath"
                    + ";AUTO_SERVER=FALSE"
                    + ";DB_CLOSE_DELAY=-1";

    // =========================================================================
    // INICIALIZACIÓN
    // =========================================================================

    /**
     * Abre (o crea) la base de datos y crea las tablas si no existen.
     * Debe llamarse una sola vez al arrancar la aplicación.
     */
    public static void inicializar() {
        try {
            Class.forName("org.h2.Driver");
            conexion = DriverManager.getConnection(RUTA_DB, "cybermath", "protocol_zero");
            crearTablas();
            System.out.println("[DB] Base de datos H2 inicializada correctamente.");
        } catch (Exception e) {
            System.err.println("[DB ERROR] No se pudo inicializar H2: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /** Cierra la conexión al cerrar la app (llamar en Application.stop()). */
    public static void cerrar() {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
                System.out.println("[DB] Conexión cerrada.");
            }
        } catch (SQLException e) {
            System.err.println("[DB ERROR] Al cerrar: " + e.getMessage());
        }
    }

    private static void crearTablas() throws SQLException {
        String sqlPartidas =
                "CREATE TABLE IF NOT EXISTS partidas (" +
                        "  slot               INTEGER PRIMARY KEY," +
                        "  nombre             VARCHAR(50)  NOT NULL," +
                        "  integridad         INTEGER      NOT NULL DEFAULT 100," +
                        "  criptos            INTEGER      NOT NULL DEFAULT 0," +
                        "  niveles_completados VARCHAR(200) NOT NULL DEFAULT ''" +
                        ")";

        String sqlHistorial =
                "CREATE TABLE IF NOT EXISTS historial (" +
                        "  id        INTEGER     GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                        "  slot      INTEGER     NOT NULL," +
                        "  nivel     INTEGER     NOT NULL," +
                        "  resultado VARCHAR(10) NOT NULL," +   // 'EXITO' o 'FALLO'
                        "  motivo    VARCHAR(30)," +
                        "  fecha     TIMESTAMP   DEFAULT CURRENT_TIMESTAMP," +
                        "  FOREIGN KEY (slot) REFERENCES partidas(slot) ON DELETE CASCADE" +
                        ")";

        try (Statement stmt = conexion.createStatement()) {
            stmt.execute(sqlPartidas);
            stmt.execute(sqlHistorial);
        }
    }

    // =========================================================================
    // OPERACIONES CRUD — PARTIDAS
    // =========================================================================

    /** Guarda o actualiza una partida en el slot indicado (UPSERT). */
    public static void guardarUsuario(Usuario usuario, int slot) {
        String sql =
                "MERGE INTO partidas (slot, nombre, integridad, criptos, niveles_completados) " +
                        "KEY(slot) VALUES (?, ?, ?, ?, ?)";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            ps.setString(2, usuario.getNombre());
            ps.setInt(3, usuario.getIntegridad());
            ps.setInt(4, usuario.getCriptos());
            ps.setString(5, serializarNiveles(usuario));
            ps.executeUpdate();
            System.out.println("[DB] Partida guardada — Slot " + slot);
        } catch (SQLException e) {
            System.err.println("[DB ERROR] guardarUsuario: " + e.getMessage());
        }
    }

    /** Carga un Usuario desde el slot. Retorna null si el slot está vacío. */
    public static Usuario cargarUsuario(int slot) {
        String sql = "SELECT * FROM partidas WHERE slot = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                Usuario u = new Usuario(rs.getString("nombre"));
                u.setIntegridad(rs.getInt("integridad"));
                u.setCriptos(rs.getInt("criptos"));
                deserializarNiveles(u, rs.getString("niveles_completados"));
                return u;
            }
        } catch (SQLException e) {
            System.err.println("[DB ERROR] cargarUsuario slot " + slot + ": " + e.getMessage());
        }
        return null;
    }

    /** Borra permanentemente la partida del slot (Permadeath). */
    public static void borrarUsuario(int slot) {
        String sql = "DELETE FROM partidas WHERE slot = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            int filas = ps.executeUpdate();
            if (filas > 0) System.out.println("[DB] Perfil slot " + slot + " purgado.");
        } catch (SQLException e) {
            System.err.println("[DB ERROR] borrarUsuario: " + e.getMessage());
        }
    }

    // =========================================================================
    // OPERACIONES — HISTORIAL
    // =========================================================================

    /** Registra el resultado de un intento en un nivel. */
    public static void registrarHistorial(int slot, int nivel, String resultado, String motivo) {
        String sql = "INSERT INTO historial (slot, nivel, resultado, motivo) VALUES (?, ?, ?, ?)";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            ps.setInt(2, nivel);
            ps.setString(3, resultado);
            ps.setString(4, motivo);
            ps.executeUpdate();
        } catch (SQLException e) {
            System.err.println("[DB ERROR] registrarHistorial: " + e.getMessage());
        }
    }

    /** Retorna estadísticas del jugador: [intentos_totales, exitos, fallos]. */
    public static int[] obtenerEstadisticas(int slot) {
        String sql =
                "SELECT COUNT(*) AS total, " +
                        "SUM(CASE WHEN resultado='EXITO' THEN 1 ELSE 0 END) AS exitos, " +
                        "SUM(CASE WHEN resultado='FALLO' THEN 1 ELSE 0 END) AS fallos " +
                        "FROM historial WHERE slot = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return new int[]{
                        rs.getInt("total"),
                        rs.getInt("exitos"),
                        rs.getInt("fallos")
                };
            }
        } catch (SQLException e) {
            System.err.println("[DB ERROR] obtenerEstadisticas: " + e.getMessage());
        }
        return new int[]{0, 0, 0};
    }

    // =========================================================================
    // SERIALIZACIÓN DE NIVELES COMPLETADOS
    // Los niveles se guardan como cadena de enteros separados por comas.
    // Ejemplo: "1,3,5,12" → niveles 1, 3, 5 y 12 completados.
    // =========================================================================

    private static String serializarNiveles(Usuario u) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 55; i++) {
            if (u.isNivelCompletado(i)) {
                if (sb.length() > 0) sb.append(",");
                sb.append(i);
            }
        }
        return sb.toString();
    }

    private static void deserializarNiveles(Usuario u, String datos) {
        if (datos == null || datos.isBlank()) return;
        for (String parte : datos.split(",")) {
            try {
                u.completarNivel(Integer.parseInt(parte.trim()));
            } catch (NumberFormatException e) {
                System.err.println("[DB WARN] Nivel inválido en BD: '" + parte + "'");
            }
        }
    }
}