package com.cybermath;

import java.sql.*;

/**
 * GestorDB — Capa de persistencia con H2 (base de datos embebida).
 * VERSIÓN TÁCTICA 2.0: Soporte para Habilidades, Minería, Skins y Bóveda de Lore.
 *
 * Ubicación del archivo: ~/CyberMathSaves/cybermath.mv.db
 */
public class GestorDB {

    // --- Conexión única (singleton) reutilizada en toda la sesión ---
    private static Connection conexion = null;

    // Ruta del archivo H2 en el directorio del usuario
    private static final String RUTA_DB =
            "jdbc:h2:" + System.getProperty("user.home")
                    + "/CyberMathSaves/cybermath"
                    + ";AUTO_SERVER=FALSE"
                    + ";DB_CLOSE_DELAY=-1";

    // =========================================================================
    // INICIALIZACIÓN Y KERNEL DB
    // =========================================================================

    /**
     * Abre (o crea) la base de datos y crea las tablas si no existen.
     */
    public static void inicializar() {
        try {
            Class.forName("org.h2.Driver");
            conexion = DriverManager.getConnection(RUTA_DB, "cybermath", "protocol_zero");
            crearTablas();
            System.out.println("[DB] Núcleo H2 inicializado. Esquema táctico verificado.");
        } catch (Exception e) {
            System.err.println("[DB ERROR] Fallo crítico al inicializar H2: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /** Cierra la conexión de forma segura. */
    public static void cerrar() {
        try {
            if (conexion != null && !conexion.isClosed()) {
                conexion.close();
                System.out.println("[DB] Conexión cerrada. Datos asegurados.");
            }
        } catch (SQLException e) {
            System.err.println("[DB ERROR] Al cerrar conexión: " + e.getMessage());
        }
    }

    private static void crearTablas() throws SQLException {
        String sqlPartidas = "CREATE TABLE IF NOT EXISTS partidas (slot INTEGER PRIMARY KEY, nombre VARCHAR(50) NOT NULL, integridad INTEGER NOT NULL DEFAULT 100, criptos INTEGER NOT NULL DEFAULT 0, niveles_completados VARCHAR(200) NOT NULL DEFAULT '')";
        String sqlHistorial = "CREATE TABLE IF NOT EXISTS historial (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, slot INTEGER NOT NULL, nivel INTEGER NOT NULL, resultado VARCHAR(10) NOT NULL, motivo VARCHAR(30), fecha TIMESTAMP DEFAULT CURRENT_TIMESTAMP, FOREIGN KEY (slot) REFERENCES partidas(slot) ON DELETE CASCADE)";

        try (Statement stmt = conexion.createStatement()) {
            stmt.execute(sqlPartidas); stmt.execute(sqlHistorial);
            // AUTO-MIGRACIÓN
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS energia INTEGER NOT NULL DEFAULT 0");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS mineros INTEGER NOT NULL DEFAULT 0");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS bonus_tiempo INTEGER NOT NULL DEFAULT 0");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS tema_ui VARCHAR(20) NOT NULL DEFAULT 'NEON'");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS lore_desbloqueado VARCHAR(50) NOT NULL DEFAULT ''");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS deep_web_score INTEGER NOT NULL DEFAULT 0");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS pistas_musica VARCHAR(50) NOT NULL DEFAULT '0'");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS temas_desbloqueados VARCHAR(30) NOT NULL DEFAULT 'NEON'");
            stmt.execute("ALTER TABLE partidas ADD COLUMN IF NOT EXISTS niveles_castigados VARCHAR(200) NOT NULL DEFAULT ''");
        }
    }

    public static void guardarUsuario(Usuario u, int slot) {
        String sql = "MERGE INTO partidas (slot, nombre, integridad, criptos, energia, mineros, bonus_tiempo, niveles_completados, tema_ui, lore_desbloqueado, deep_web_score, pistas_musica, temas_desbloqueados, niveles_castigados) KEY(slot) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot); ps.setString(2, u.getNombre()); ps.setInt(3, u.getIntegridad());
            ps.setInt(4, u.getCriptos()); ps.setInt(5, u.getEnergia()); ps.setInt(6, u.getMineros());
            ps.setInt(7, u.getBonusTiempo()); ps.setString(8, serializarNiveles(u));
            ps.setString(9, u.getTemaUI());

            StringBuilder loreStr = new StringBuilder();
            for(int i=0; i<5; i++) if(u.isLoreDesbloqueado(i)) loreStr.append(i).append(",");
            ps.setString(10, loreStr.toString());

            ps.setInt(11, u.getDeepWebScore());

            StringBuilder pistasStr = new StringBuilder();
            for(int i=0; i<3; i++) if(u.isPistaDesbloqueada(i)) pistasStr.append(i).append(",");
            ps.setString(12, pistasStr.toString());

            StringBuilder temasStr = new StringBuilder("NEON");
            if (u.isTemaDesbloqueado("AMBAR")) temasStr.append(",AMBAR");
            if (u.isTemaDesbloqueado("AZUL"))  temasStr.append(",AZUL");
            ps.setString(13, temasStr.toString());

            StringBuilder castigosStr = new StringBuilder();
            for (int n : u.getNivelesCastigados()) castigosStr.append(n).append(",");
            ps.setString(14, castigosStr.toString());

            ps.executeUpdate();
        } catch (SQLException e) { System.err.println("[DB ERROR] guardarUsuario: " + e.getMessage()); }
    }

    public static Usuario cargarUsuario(int slot) {
        String sql = "SELECT * FROM partidas WHERE slot = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot); ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                Usuario u = new Usuario(rs.getString("nombre"));
                u.setIntegridad(rs.getInt("integridad")); u.setCriptos(rs.getInt("criptos"));
                u.setEnergia(rs.getInt("energia")); u.setMineros(rs.getInt("mineros"));
                u.setBonusTiempo(rs.getInt("bonus_tiempo")); u.setTemaUI(rs.getString("tema_ui"));
                deserializarNiveles(u, rs.getString("niveles_completados"));

                String loreStr = rs.getString("lore_desbloqueado");
                if (loreStr != null) for (String p : loreStr.split(",")) if(!p.isBlank()) u.desbloquearLore(Integer.parseInt(p.trim()));

                u.setDeepWebScore(rs.getInt("deep_web_score"));

                String pistasStr = rs.getString("pistas_musica");
                if (pistasStr != null) for (String p : pistasStr.split(",")) if(!p.isBlank()) u.desbloquearPista(Integer.parseInt(p.trim()));

                String temasStr = rs.getString("temas_desbloqueados");
                if (temasStr != null) {
                    if (temasStr.contains("AMBAR")) u.desbloquearTema("AMBAR");
                    if (temasStr.contains("AZUL"))  u.desbloquearTema("AZUL");
                }

                String castigosStr = rs.getString("niveles_castigados");
                if (castigosStr != null && !castigosStr.isBlank()) {
                    java.util.List<Integer> castigos = new java.util.ArrayList<>();
                    for (String p : castigosStr.split(","))
                        if (!p.isBlank()) castigos.add(Integer.parseInt(p.trim()));
                    u.setNivelesCastigados(castigos);
                }

                return u;
            }
        } catch (SQLException e) { System.err.println("[DB ERROR] cargarUsuario: " + e.getMessage()); }
        return null;
    }
    /** Borra permanentemente la partida del slot (Permadeath). */
    public static void borrarUsuario(int slot) {
        String sql = "DELETE FROM partidas WHERE slot = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            int filas = ps.executeUpdate();
            if (filas > 0) System.out.println("[DB] Perfil slot " + slot + " purgado definitivamente.");
        } catch (SQLException e) {
            System.err.println("[DB ERROR] borrarUsuario: " + e.getMessage());
        }
    }

    // =========================================================================
    // OPERACIONES — HISTORIAL Y ESTADÍSTICAS
    // =========================================================================

    /** Registra el resultado de un intento de hackeo en un nivel. */
    public static void registrarHistorial(int slot, int nivel, String resultado, String motivo) {
        String sql = "INSERT INTO historial (slot, nivel, resultado, motivo) VALUES (?, ?, ?, ?)";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            ps.setInt(2, nivel);
            ps.setString(3, resultado);
            ps.setString(4, motivo);
            ps.executeUpdate();
        } catch (SQLException e) {
            System.err.println("[DB ERROR] registrarHistorial: " + e.getMessage());
        }
    }

    /** Retorna estadísticas del jugador: [intentos_totales, exitos, fallos]. */
    public static int[] obtenerEstadisticas(int slot) {
        String sql =
                "SELECT COUNT(*) AS total, " +
                        "SUM(CASE WHEN resultado='EXITO' THEN 1 ELSE 0 END) AS exitos, " +
                        "SUM(CASE WHEN resultado='FALLO' THEN 1 ELSE 0 END) AS fallos " +
                        "FROM historial WHERE slot = ?";
        try (PreparedStatement ps = conexion.prepareStatement(sql)) {
            ps.setInt(1, slot);
            ResultSet rs = ps.executeQuery();
            if (rs.next()) {
                return new int[]{
                        rs.getInt("total"),
                        rs.getInt("exitos"),
                        rs.getInt("fallos")
                };
            }
        } catch (SQLException e) {
            System.err.println("[DB ERROR] obtenerEstadisticas: " + e.getMessage());
        }
        return new int[]{0, 0, 0};
    }

    // =========================================================================
    // HERRAMIENTAS DE SERIALIZACIÓN
    // =========================================================================

    private static String serializarNiveles(Usuario u) {
        StringBuilder sb = new StringBuilder();
        for (int i = 0; i < 55; i++) {
            if (u.isNivelCompletado(i)) {
                if (sb.length() > 0) sb.append(",");
                sb.append(i);
            }
        }
        return sb.toString();
    }

    private static void deserializarNiveles(Usuario u, String datos) {
        if (datos == null || datos.isBlank()) return;
        for (String parte : datos.split(",")) {
            try {
                if(!parte.trim().isEmpty()) {
                    u.completarNivel(Integer.parseInt(parte.trim()));
                }
            } catch (NumberFormatException e) {
                System.err.println("[DB WARN] Nivel inválido en BD: '" + parte + "'");
            }
        }
    }
}